/*
 * mysqlTypes.h
 *
 *  Created on: 2018年12月5日
 *      Author: liwei
 */

#ifndef MYSQLTYPES_H_
#define MYSQLTYPES_H_
#include "columnType.h"
	typedef enum MysqlFiledType {
		MYSQL_TYPE_DECIMAL, MYSQL_TYPE_TINY,
		MYSQL_TYPE_SHORT, MYSQL_TYPE_LONG,
		MYSQL_TYPE_FLOAT, MYSQL_TYPE_DOUBLE,
		MYSQL_TYPE_NULL, MYSQL_TYPE_TIMESTAMP,
		MYSQL_TYPE_LONGLONG, MYSQL_TYPE_INT24,
		MYSQL_TYPE_DATE, MYSQL_TYPE_TIME,
		MYSQL_TYPE_DATETIME, MYSQL_TYPE_YEAR,
		MYSQL_TYPE_NEWDATE, MYSQL_TYPE_VARCHAR,
		MYSQL_TYPE_BIT,
		MYSQL_TYPE_TIMESTAMP2,
		MYSQL_TYPE_DATETIME2,
		MYSQL_TYPE_TIME2,
		MYSQL_TYPE_JSON = 245,
		MYSQL_TYPE_NEWDECIMAL = 246,
		MYSQL_TYPE_ENUM = 247,
		MYSQL_TYPE_SET = 248,
		MYSQL_TYPE_TINY_BLOB = 249,
		MYSQL_TYPE_MEDIUM_BLOB = 250,
		MYSQL_TYPE_LONG_BLOB = 251,
		MYSQL_TYPE_BLOB = 252,
		MYSQL_TYPE_VAR_STRING = 253,
		MYSQL_TYPE_STRING = 254,
		MYSQL_TYPE_GEOMETRY = 255
	} enum_field_types;
	constexpr uint8_t mysqlTypeMaps[] = { T_DECIMAL,T_INT8,T_INT16,T_INT32,T_FLOAT,T_DOUBLE,T_MAX_TYPE,T_TIMESTAMP,T_INT64,T_INT32,T_DATE,T_TIME,T_DATETIME,T_YEAR,T_DATE,T_STRING,T_BYTE,T_TIMESTAMP,T_DATETIME,T_TIME,
	T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,
	T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,
	T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,
	T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,
	T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,
	T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,
	T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,
	T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,
	T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,
	T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,
	T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,
	T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_MAX_TYPE,T_JSON,T_DECIMAL,T_ENUM,T_SET,T_BLOB,T_BLOB,T_BLOB,T_BLOB,T_STRING,T_STRING,T_GEOMETRY
	};


#endif /* MYSQLTYPES_H_ */
